### ISSUE TITLE
widget doesn't refresh

### ISSUE THREAD

**Issue by hj-beckers** [sanderbaas/WeatherWidget#10]
As the title says, neither automagically every 30 minutes or by tap-ping the widget.

I have to tap the settings icon, must reenter the (same) location and select "add widget". This is on a Samsung Galaxy Note 4, Android 6.0.1.

1. Enhancement wish: a store for more locations, make them selectable.

2. Enhancement wish: Could you be more specific with the name? I have now 3 weather apps, all called "Wetter" in a german UI.

Thank you

**Comment by sanderbaas** [comment]
I can reproduce the issue of not refreshing on the dark widget, but not the light widget. That seems to work and may be a workaround for now. I am going to fix it.

**Comment by sanderbaas** [comment]
Moved your enhancement wishes to separate issues.
#11 and #12 .
