### ISSUE TITLE
Incompatible with popular Android devices

### ISSUE THREAD

**Issue by HiFromAjay** [sanderbaas/WeatherWidget#13]
The app supports min SDK 23, which is incompatible with some of the popular Android devices currently in use such as Galaxy J2, J1 Ace, Grand Prime, and Oppo A37f. These Android devices support min SDK 22.

**Comment by jspricke** [comment]
This makes it impossible to upgrade from 1.3.2 to 1.3.3 (using F-Droid). The resulting error is:
`Error -26: null`
and adb logcat gives:
`PackageManager: Package nl.implode.weer new target SDK 22 doesn't support runtime permissions but the old target SDK 23 does.`

**Comment by Bubu** [comment]
Note the difference between target and minsdk. You can keep minsdk low but you must now keep targetsdk at >=23 or anyone who has 1.3.2 installed cannot install any updates any more.

**Comment by sanderbaas** [comment]
Thanks, I'll look into it tomorrow.
