### ISSUE TITLE
Time display switch doesn't work as expected

### ISSUE THREAD

**Issue by Buntbart** [sanderbaas/WeatherWidget#16]
Device: Samsung Galaxy S5
OS: LineageOS 16 (Android 9)
No Google Play Services installed
App-Version: 1.3.4
Source of app: F-Droid

I have set the widget to a place in another timezone and switched the settings to "Use local time instead of device time".

I expected the widget to sort the display according to the time for the set location, but I can't see any effect of the switch.

So I guess I misunderstood the meaning of the switch. Nevertheless, I would be interested if the widget could not align the display as if you were in the respective time zone.

**Comment by sanderbaas** [comment]
You are right, that is what it should do. However, it doesn't. I will look at it. Thanks

**Comment by sanderbaas** [comment]
fixed in version 1.3.5
