### ISSUE TITLE
Widget doesn't refresh

### ISSUE THREAD

**Issue by Sammala** [sanderbaas/WeatherWidget#17]
Device: Nokia 5
Android version: 9
Widget version:  Version 1.3.5 

After upgrading to version 1.3.5, the time doesn't automatically refresh and cannot be refreshed by tapping the widget. It doesn't work on both the light or dark version. The only way to refresh it is by re-entering your location. 
I've faced a similar bug on an earlier version of this widget, cannot remember which one it was though.

On 1.3.4, the widget worked fine for me. However, my father (Nokia 8, Android 9) had the same issue on 1.3.4. I honestly have no idea what the cause of this problem might be or how you could reproduce it. 

I hope you can fix it because this is the best weather widget that I know of! :)

**Comment by sanderbaas** [comment]
Thank you for bringing this to my attention. Starting with android version 8, handling of background processes have changed. This has influence on the service that updates the widget automatically. I am still looking into this, but in the mean time try adding the app to the list of apps that are not optimized as a workaround. You can do this as follows: Go to settings > apps & notifications > Special app access > Battery optimization. Then change from 'Not optimized' to 'All apps' click 'Weather Widget' and select 'Don't optimize'.

**Comment by Sammala** [comment]
Thank you, the workaround did indeed work! :)
(Sorry for the late reply, I was on vacation.)
