### ISSUE TITLE
Widget changes theme from dark to light when refreshing

### ISSUE THREAD

**Issue by guest4711** [sanderbaas/WeatherWidget#18]
Thanks for the new f-droid version (1.4.0). Now refreshing of the widget is working even on Pie. 
I'm using the dark widget. But every morning I'll be greated by the light one. This is new on 1.4.0.

**Comment by sanderbaas** [comment]
Thank you. I'll look into it.

**Comment by guest4711** [comment]
Thank you. Working fine now. New version is in f-droid store.

**Comment by guest4711** [comment]
Same problem when changing location: Dark widget changes to light one..
