### ISSUE TITLE
No widget at all

### ISSUE THREAD

**Issue by motor-glider** [sanderbaas/WeatherWidget#21]
Hello,
I don't get any widget to place on the home screen at al, even after removing and reinstalling the appl. Galaxy Tab SM-T700 running Android 7.1.2 - what am I doing wrong? What's possible to debug that behaviour?

**Comment by sanderbaas** [comment]
Hi,
I have just tested the app on an Nexus 10 emulator with Android Oreo (7.1.1). The Nexus 10 should have the same screen dimensions as your Galaxy Tab SM-T700.

Could you describe your problem more precisely? Do you see the available widgets after long pressing your wallpaper and then tapping 'widgets'? When you drag the widget to a home screen, do you get the screen to search for a location?

**Comment by motor-glider** [comment]
Hello Sander,

that's exactly my problem - I don't see any widget available in
"Widgets" after long tap on the homescreen. The Problem remains, even
after a reboot. Is there a way to add a widget "manually", e.g. using
adb shell? OS is a Resurrection Remix (Android 7.1.2)

I have some experience in Unixes incl. Linux for ~20 years incl.
programming in different languages, but not really with Android except
using the OS shell, so if you could explain, I'd like to try it out.

Kind regards,
Eckard


Am Sat, 24 Aug 2019 04:11:17 -0700
schrieb Sander Baas <notifications@github.com>:

> Hi,
> I have just tested the app on an Nexus 10 emulator with Android Oreo
> (7.1.1). The Nexus 10 should have the same screen dimensions as your
> Galaxy Tab SM-T700.
> 
> Could you describe your problem more precisely? Do you see the
> available widgets after long pressing your wallpaper and then tapping
> 'widgets'? When you drag the widget to a home screen, do you get the
> screen to search for a location?
> 



-- 
Wir haften nicht für die korrekte Funktion der in dieser eMail
enthaltenen Viren. We are not liable for correct function of the
viruses in this email! :)

**Comment by sanderbaas** [comment]
Hi Eckard,

I'm not sure if it's possible to add a widget with adb shell.

Could you please check the dimensions of your screen with this app for example (https://f-droid.org/en/packages/com.jotabout.screeninfo/). The widgets are only available if the defined minimal screen size is available. For the widgets this is 250dp for the width and height.

**Comment by motor-glider** [comment]
Hi Sander,

thanks for the response and support.

Screeninfo gives me that exact information:

Device Name: SM-T700
Android Version: 7.1.2
Screen class: large
Density class: Unknown
Total Width (px): 1600
Total Height (px): 2560
App-usable Width (px): 1600
App-usable Height (px): 2560
Width (dp): 600
Height (dp): 962
Smallest DP: 600
Long or Wide: No
Natural Orientation: Portrait
Current Orientation: 0
Touchscreen: Finger
Screen DPI: 426
X DPI: 359.646
Y DPI: 361.244
Logical Density: 2.6625001430511475
Font Scale Density: 2.6625001
Calculated Diagonal (inches): 8.4
Calculated Diagonal (mm): 213.0
Pixel Format: Not Available
Refresh Rate (fps): 60.000004

Is there something unusual in? 

Best regards,
Eckard

Am Sun, 25 Aug 2019 05:17:08 -0700
schrieb Sander Baas <notifications@github.com>:

> Hi Eckard,
> 
> I'm not sure if it's possible to add a widget with adb shell.
> 
> Could you please check the dimensions of your screen with this app
> for example
> (https://f-droid.org/en/packages/com.jotabout.screeninfo/). The
> widgets are only available if the defined minimal screen size is
> available. For the widgets this is 250dp for the width and height. 
> 



-- 
Wir haften nicht für die korrekte Funktion der in dieser eMail
enthaltenen Viren. We are not liable for correct function of the
viruses in this email! :)

**Comment by sanderbaas** [comment]
I don't see anything unusual in this report. Unfortunately it's really hard for me to debug when I can't reproduce it. Perhaps this is a known issue for Resurrection Remix?
