### ISSUE TITLE
White margin at the bottom

### ISSUE THREAD

**Issue by zeehio** [sanderbaas/WeatherWidget#26]
Hi,

Thanks for your widget. It is very informative.

I tried to use it at a larger size to get more predictions. It works, but I get a quite large white space at the bottom. 

![Screenshot_20191225-042437](https://user-images.githubusercontent.com/75441/71443106-baf5a280-26ce-11ea-946b-a70ead9e7506.png)

Is it possible to get a tighter layout? If I make it a bit smaller, then the last row disappears, even if it would fit in my eyes:

![Screenshot_20191225-043009](https://user-images.githubusercontent.com/75441/71443212-56871300-26cf-11ea-9519-4ab8af000966.png)

I am using the Nova Launcher if that matters.

**Comment by sanderbaas** [comment]
I will look at this. I agree that it looks like an extra row would fit...
